export const RESET_SEARCH = "RESET_SEARCH";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SET_SEARCH_OFFSET = "SET_SEARCH_OFFSET";

export const SET_SEARCH_OFF_BY_ARTIST = "SET_SEARCH_OFF_BY_ARTIST";

export const SET_SEARCH_OFF_BY_ALBUM = "SET_SEARCH_OFF_BY_ALBUM";

export const SET_SEARCH_OFF_BY_SONG = "SET_SEARCH_OFF_BY_SONG";

export const SET_MEDIA_COLLECTION = "SET_MEDIA_COLLECTION";

export const SET_COLLECTION_SIZE = "SET_COLLECTION_SIZE";

export const SET_RESULTS_LOAD_FINISHED = "SET_RESULTS_LOAD_FINISHED";