export const RESET_SEARCH = "RESET_SEARCH";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SET_SEARCH_OFF_BY_ARTIST = "SET_SEARCH_OFF_BY_ARTIST";

export const SET_SEARCH_OFF_BY_ALBUM = "SET_SEARCH_OFF_BY_ALBUM";

export const SET_SEARCH_OFF_BY_SONG = "SET_SEARCH_OFF_BY_SONG";

export const SET_MEDIA_COLLECTION = "SET_MEDIA_COLLECTION";

export const SET_RESULTS_LOAD_FINISHED = "SET_RESULTS_LOAD_FINISHED";

export const SET_ARTIST_LIST = "SET_ARTIST_LIST";

export const SET_ALBUM_LIST = "SET_ALBUM_LIST";

export const SET_SONG_LIST = "SET_SONG_LIST";

export const UPDATE_OFFSET_ARTIST = "UPDATE_OFFSET_ARTIST";

export const UPDATE_OFFSET_ALBUM = "UPDATE_OFFSET_ALBUM";

export const UPDATE_OFFSET_SONG = "UPDATE_OFFSET_SONG";

export const SET_REQUEST_ERROR = "SET_REQUEST_ERROR";